/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    price: bigint;
}
export interface AddProductParams {
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    price: bigint;
}
export type Time = bigint;
export interface Sponsor {
    id: bigint;
    name: string;
    description: string;
    logoUrl: string;
}
export interface OrderItem {
    productName: string;
    quantity: bigint;
    unitPrice: bigint;
}
export interface BackendOrder {
    total: bigint;
    paymentMethod: string;
    deliveryDetails: DeliveryDetails;
    timestamp: Time;
    quantity: bigint;
    items: Array<OrderItem>;
}
export interface EditProductParams {
    id: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    price: bigint;
}
export interface DeliveryDetails {
    fullName: string;
    email: string;
    address: string;
    phoneNumber: string;
}
export enum Category {
    clothing = "clothing",
    other = "other",
    accessorie = "accessorie",
    electronics = "electronics"
}
export interface backendInterface {
    addProduct(params: AddProductParams): Promise<bigint>;
    addSponsor(name: string, logoUrl: string, description: string): Promise<void>;
    deleteProduct(id: bigint): Promise<void>;
    deleteSponsor(id: bigint): Promise<void>;
    editProduct(params: EditProductParams): Promise<void>;
    editSponsor(id: bigint, name: string, logoUrl: string, description: string): Promise<void>;
    getAllProducts(): Promise<Array<Product>>;
    getAllSponsors(): Promise<Array<Sponsor>>;
    getOrders(): Promise<Array<BackendOrder>>;
    getProductsByCategory(category: Category): Promise<Array<Product>>;
    placeOrder(fullName: string, email: string, phoneNumber: string, address: string, items: Array<OrderItem>, total: bigint): Promise<bigint>;
    redeemLoyaltyPoints(payerId: string, amount: bigint): Promise<void>;
}
import type { AddProductParams as _AddProductParams, Category as _Category, EditProductParams as _EditProductParams, Product as _Product } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addProduct(arg0: AddProductParams): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_AddProductParams_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_AddProductParams_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSponsor(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSponsor(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSponsor(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteSponsor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSponsor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSponsor(arg0);
            return result;
        }
    }
    async editProduct(arg0: EditProductParams): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editProduct(to_candid_EditProductParams_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editProduct(to_candid_EditProductParams_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async editSponsor(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editSponsor(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editSponsor(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSponsors(): Promise<Array<Sponsor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSponsors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSponsors();
            return result;
        }
    }
    async getOrders(): Promise<Array<BackendOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return result;
        }
    }
    async getProductsByCategory(arg0: Category): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<OrderItem>, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async redeemLoyaltyPoints(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemLoyaltyPoints(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemLoyaltyPoints(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Category_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: _Category;
    price: bigint;
}): {
    id: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    price: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl,
        category: from_candid_Category_n10(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clothing: null;
} | {
    other: null;
} | {
    accessorie: null;
} | {
    electronics: null;
}): Category {
    return "clothing" in value ? Category.clothing : "other" in value ? Category.other : "accessorie" in value ? Category.accessorie : "electronics" in value ? Category.electronics : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n8(_uploadFile, _downloadFile, x));
}
function to_candid_AddProductParams_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddProductParams): _AddProductParams {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_EditProductParams_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EditProductParams): _EditProductParams {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    price: bigint;
}): {
    name: string;
    description: string;
    imageUrl: string;
    category: _Category;
    price: bigint;
} {
    return {
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: Category;
    price: bigint;
}): {
    id: bigint;
    name: string;
    description: string;
    imageUrl: string;
    category: _Category;
    price: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    clothing: null;
} | {
    other: null;
} | {
    accessorie: null;
} | {
    electronics: null;
} {
    return value == Category.clothing ? {
        clothing: null
    } : value == Category.other ? {
        other: null
    } : value == Category.accessorie ? {
        accessorie: null
    } : value == Category.electronics ? {
        electronics: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
