/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddProductParams {
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'price' : bigint,
}
export interface BackendOrder {
  'total' : bigint,
  'paymentMethod' : string,
  'deliveryDetails' : DeliveryDetails,
  'timestamp' : Time,
  'quantity' : bigint,
  'items' : Array<OrderItem>,
}
export type Category = { 'clothing' : null } |
  { 'other' : null } |
  { 'accessorie' : null } |
  { 'electronics' : null };
export interface DeliveryDetails {
  'fullName' : string,
  'email' : string,
  'address' : string,
  'phoneNumber' : string,
}
export interface EditProductParams {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'price' : bigint,
}
export interface OrderItem {
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'price' : bigint,
}
export interface Sponsor {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'logoUrl' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addProduct' : ActorMethod<[AddProductParams], bigint>,
  'addSponsor' : ActorMethod<[string, string, string], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteSponsor' : ActorMethod<[bigint], undefined>,
  'editProduct' : ActorMethod<[EditProductParams], undefined>,
  'editSponsor' : ActorMethod<[bigint, string, string, string], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllSponsors' : ActorMethod<[], Array<Sponsor>>,
  'getOrders' : ActorMethod<[], Array<BackendOrder>>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'placeOrder' : ActorMethod<
    [string, string, string, string, Array<OrderItem>, bigint],
    bigint
  >,
  'redeemLoyaltyPoints' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];