/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'clothing' : IDL.Null,
  'other' : IDL.Null,
  'accessorie' : IDL.Null,
  'electronics' : IDL.Null,
});
export const AddProductParams = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});
export const EditProductParams = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});
export const Sponsor = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'logoUrl' : IDL.Text,
});
export const DeliveryDetails = IDL.Record({
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const Time = IDL.Int;
export const OrderItem = IDL.Record({
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const BackendOrder = IDL.Record({
  'total' : IDL.Nat,
  'paymentMethod' : IDL.Text,
  'deliveryDetails' : DeliveryDetails,
  'timestamp' : Time,
  'quantity' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([AddProductParams], [IDL.Nat], []),
  'addSponsor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteSponsor' : IDL.Func([IDL.Nat], [], []),
  'editProduct' : IDL.Func([EditProductParams], [], []),
  'editSponsor' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllSponsors' : IDL.Func([], [IDL.Vec(Sponsor)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(BackendOrder)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem), IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'redeemLoyaltyPoints' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'clothing' : IDL.Null,
    'other' : IDL.Null,
    'accessorie' : IDL.Null,
    'electronics' : IDL.Null,
  });
  const AddProductParams = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const EditProductParams = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const Sponsor = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'logoUrl' : IDL.Text,
  });
  const DeliveryDetails = IDL.Record({
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const Time = IDL.Int;
  const OrderItem = IDL.Record({
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const BackendOrder = IDL.Record({
    'total' : IDL.Nat,
    'paymentMethod' : IDL.Text,
    'deliveryDetails' : DeliveryDetails,
    'timestamp' : Time,
    'quantity' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([AddProductParams], [IDL.Nat], []),
    'addSponsor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteSponsor' : IDL.Func([IDL.Nat], [], []),
    'editProduct' : IDL.Func([EditProductParams], [], []),
    'editSponsor' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllSponsors' : IDL.Func([], [IDL.Vec(Sponsor)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(BackendOrder)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem), IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'redeemLoyaltyPoints' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };